### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by benmccann**
Wanted to get a fixed version of webjars-locator-core with jroper's zip fix

### CODE REVIEW

**Comment by jamesward** [comment]
@benmccann Can you fix up the tests for this?

**Comment by benmccann** [comment]
@jamesward the error message is `java.lang.UnsupportedClassVersionError: org/webjars/WebJarAssetLocator`, so it looks like `webjars-locator-core` was compiled on Java 7.  i'm going to drop java 6 from the `travis.yml` if you have no objections

**Comment by benmccann** [comment]
@jamesward tests are passing now

**Comment by jamesward** [comment]
Thanks! Releasing this shortly.

**Pull request merged**
